In [1]:
import numpy as np
a=np.array([1,2,3])
print(a)

[1 2 3]


In [2]:
b=np.array((3,5))
print(b)

[3 5]


In [3]:
a = np.array([[1,2,3], [4,5,6]])
a.ndim

2

In [4]:
a[1,1]

5

In [7]:
B = np.array([[1,2,4,9,1],[2,1,4,9,10]])

In [8]:
B[1,2]

4

In [9]:
C= np.array([[[1,3,4],[1,0,4]],[[2,1,0],[0,9,5]]])

In [13]:
B[1,3]

9

In [14]:
C.ndim

3

In [3]:
import numpy as np
C= np.array([[[1,3,4],[1,0,4]],[[2,1,0],[0,9,5]]])
C.size

12

In [4]:
C.nbytes

48

In [5]:
np.zeros

<function numpy.zeros>

In [9]:
import numpy as np

In [10]:

A= np.arange(11)

In [11]:
print (A)

[ 0  1  2  3  4  5  6  7  8  9 10]


In [14]:
B= np.arange(2004,2021,2)

In [20]:
print(B)

[2004 2005 2006 2007 2008 2009 2010 2011 2012 2013 2014 2015 2016 2017
 2018 2019 2020]


In [19]:
C= np.arange(2004,2021,2)
print(C)

[2004 2006 2008 2010 2012 2014 2016 2018 2020]


In [7]:
print (list(range(10,20,2)))

[10, 12, 14, 16, 18]


In [2]:
import numpy as np
print(np.random.permutation(11))

[ 7  3  6  2  4  5 10  9  8  0  1]


In [13]:
np.random.randint(10)

9

In [4]:
import numpy as np
C = np.arange(10)
C.reshape(5,2)

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7],
       [8, 9]])

In [5]:
A = np.arange(10)
b= A[2:7]
print(b)

[2 3 4 5 6]


In [6]:
b[1] = 2
print(b)

[2 2 4 5 6]


In [26]:
C= np.arange(100)
c = C[50:100]
c[23] = 9281

In [27]:
print(c)

[  50   51   52   53   54   55   56   57   58   59   60   61   62   63
   64   65   66   67   68   69   70   71   72 9281   74   75   76   77
   78   79   80   81   82   83   84   85   86   87   88   89   90   91
   92   93   94   95   96   97   98   99]


In [28]:
c= C[::-1]
print(c)

[  99   98   97   96   95   94   93   92   91   90   89   88   87   86
   85   84   83   82   81   80   79   78   77   76   75   74 9281   72
   71   70   69   68   67   66   65   64   63   62   61   60   59   58
   57   56   55   54   53   52   51   50   49   48   47   46   45   44
   43   42   41   40   39   38   37   36   35   34   33   32   31   30
   29   28   27   26   25   24   23   22   21   20   19   18   17   16
   15   14   13   12   11   10    9    8    7    6    5    4    3    2
    1    0]


In [2]:
import numpy as np
idx = np.argwhere(C==2)[0][0]

NameError: name 'C' is not defined

In [ ]:
idx

In [31]:
c

array([  99,   98,   97,   96,   95,   94,   93,   92,   91,   90,   89,
         88,   87,   86,   85,   84,   83,   82,   81,   80,   79,   78,
         77,   76,   75,   74, 9281,   72,   71,   70,   69,   68,   67,
         66,   65,   64,   63,   62,   61,   60,   59,   58,   57,   56,
         55,   54,   53,   52,   51,   50,   49,   48,   47,   46,   45,
         44,   43,   42,   41,   40,   39,   38,   37,   36,   35,   34,
         33,   32,   31,   30,   29,   28,   27,   26,   25,   24,   23,
         22,   21,   20,   19,   18,   17,   16,   15,   14,   13,   12,
         11,   10,    9,    8,    7,    6,    5,    4,    3,    2,    1,
          0])

In [32]:
idx = np.argwhere(C==9281)[0][0]

In [33]:
idx

73

In [34]:
C[idx]= 75

In [35]:
c

array([99, 98, 97, 96, 95, 94, 93, 92, 91, 90, 89, 88, 87, 86, 85, 84, 83,
       82, 81, 80, 79, 78, 77, 76, 75, 74, 75, 72, 71, 70, 69, 68, 67, 66,
       65, 64, 63, 62, 61, 60, 59, 58, 57, 56, 55, 54, 53, 52, 51, 50, 49,
       48, 47, 46, 45, 44, 43, 42, 41, 40, 39, 38, 37, 36, 35, 34, 33, 32,
       31, 30, 29, 28, 27, 26, 25, 24, 23, 22, 21, 20, 19, 18, 17, 16, 15,
       14, 13, 12, 11, 10,  9,  8,  7,  6,  5,  4,  3,  2,  1,  0])

In [38]:
A = np.round(10*np.random.rand(5,4))

In [39]:
A

array([[ 1.,  6.,  4.,  2.],
       [ 3.,  8.,  5.,  7.],
       [ 9., 10.,  5.,  8.],
       [ 8., 10.,  8.,  3.],
       [ 9.,  5.,  5.,  3.]])

In [40]:
A[1,3]

7.0

In [41]:
A[:,0]

array([1., 3., 9., 8., 9.])

In [43]:
A[0:2,0:2]

array([[1., 6.],
       [3., 8.]])

In [44]:
A.T

array([[ 1.,  3.,  9.,  8.,  9.],
       [ 6.,  8., 10., 10.,  5.],
       [ 4.,  5.,  5.,  8.,  5.],
       [ 2.,  7.,  8.,  3.,  3.]])

In [45]:
A


array([[ 1.,  6.,  4.,  2.],
       [ 3.,  8.,  5.,  7.],
       [ 9., 10.,  5.,  8.],
       [ 8., 10.,  8.,  3.],
       [ 9.,  5.,  5.,  3.]])

In [46]:
A.sort(axis=0)

In [47]:
A


array([[ 1.,  5.,  4.,  2.],
       [ 3.,  6.,  5.,  3.],
       [ 8.,  8.,  5.,  3.],
       [ 9., 10.,  5.,  7.],
       [ 9., 10.,  8.,  8.]])

In [5]:
print(np.random.permutation(10))

[0 5 7 6 9 2 8 3 1 4]


In [4]:
B


array([3, 8, 6, 4, 1, 5, 9, 0, 7, 2])

In [7]:
A = np.arange(100)

In [9]:
B = A[[2,3,4]]

In [10]:
B

array([2, 3, 4])

In [11]:
B[2] = 2
B[1] = 2

B

In [12]:
print(B)

[2 2 2]


In [13]:
A

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99])

In [14]:
A[3] = 2

In [15]:
A

array([ 0,  1,  2,  2,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99])

In [16]:
B = A[A< 40]

In [17]:
B

array([ 0,  1,  2,  2,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39])

In [22]:
B = A[A>40]

In [24]:
B

array([41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55, 56, 57,
       58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 70, 71, 72, 73, 74,
       75, 76, 77, 78, 79, 80, 81, 82, 83, 84, 85, 86, 87, 88, 89, 90, 91,
       92, 93, 94, 95, 96, 97, 98, 99])

In [25]:
B = A[(A>40) & (A%2==0)]

In [26]:
B

array([42, 44, 46, 48, 50, 52, 54, 56, 58, 60, 62, 64, 66, 68, 70, 72, 74,
       76, 78, 80, 82, 84, 86, 88, 90, 92, 94, 96, 98])

In [27]:
A = np.round(10*np.random.rand(2,3))

In [28]:
A

array([[2., 1., 8.],
       [2., 9., 7.]])

In [29]:
A+4

array([[ 6.,  5., 12.],
       [ 6., 13., 11.]])

In [37]:
B = np.round(10*np.random.rand(2,2))

In [38]:
B

array([[2., 6.],
       [2., 4.]])

In [39]:
C = np.hstack((A,B)) #np.vstack
 

In [40]:
C

array([[2., 1., 8., 2., 6.],
       [2., 9., 7., 2., 4.]])

ValueError: all the input array dimensions for the concatenation axis must match exactly, but along dimension 1, the array at index 0 has size 3 and the array at index 1 has size 2

In [42]:
A = np.random.permutation(10)

In [43]:
A

array([8, 3, 1, 6, 9, 5, 7, 2, 0, 4])

In [44]:
A.sort()

In [45]:
A

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [46]:
A

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [47]:
A= A[::-1]

In [48]:
A

array([9, 8, 7, 6, 5, 4, 3, 2, 1, 0])

In [49]:
A=A[2::]

In [50]:
A

array([7, 6, 5, 4, 3, 2, 1, 0])

In [51]:
B = np.random.rand(1000)

In [52]:
B

array([0.79851061, 0.65724585, 0.82735041, 0.00323463, 0.33238105,
       0.66416675, 0.72150442, 0.5774223 , 0.34476198, 0.29342619,
       0.86312439, 0.81786806, 0.78768322, 0.18408978, 0.00762067,
       0.69560374, 0.92275424, 0.2390586 , 0.444623  , 0.13718467,
       0.34980552, 0.09715609, 0.44525201, 0.18298013, 0.96083392,
       0.82398759, 0.68343072, 0.46953082, 0.09589756, 0.15987509,
       0.33913631, 0.73858476, 0.56035616, 0.64155115, 0.81444171,
       0.51474765, 0.51443521, 0.00826172, 0.43767877, 0.20406631,
       0.27493857, 0.12838948, 0.54085104, 0.49299633, 0.15616047,
       0.91556552, 0.69045921, 0.4690533 , 0.14887987, 0.49568989,
       0.99487258, 0.39222032, 0.88910282, 0.73037923, 0.10231075,
       0.59769714, 0.2432941 , 0.37020497, 0.82367741, 0.32044771,
       0.16882144, 0.27840399, 0.21691438, 0.37559987, 0.06400339,
       0.37646523, 0.26475527, 0.20780502, 0.97640658, 0.83035098,
       0.4929056 , 0.12777368, 0.61090904, 0.44997741, 0.27989

In [53]:
np.sum(B)

493.910430516487